FROM cyberdojofoundation/ubuntu-build-essential-18-04:a6578e6
LABEL maintainer=jon@jaggersoft.com

COPY install.sh .
RUN ./install.sh && rm ./install.sh

ENV PATH=/usr/local/clang_10.0.0/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/clang_10.0.0/lib:$LD_LIBRARY_PATH \
    CC=clang \
    CXX=clang++
