FROM ghcr.io/cyber-dojo-languages/ubuntu-build-essential-24-04:8ab6c08
LABEL maintainer=jon@jaggersoft.com

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --yes \
  clang \
  llvm \
  gcovr

ENV CC=clang \
    CXX=clang++
